### ISSUE TITLE
数组的排序方法有些问题

### ISSUE THREAD

**Issue by belief-cyf** [xuliangzhan/xe-utils#12]
![image](https://user-images.githubusercontent.com/19991842/83122127-c463ba80-a105-11ea-950a-9a8fd8cdc1c0.png)
如图所示

排序有时候有数字和字符串混合的情况  这种时候排序的结果不是逾期那样的。

**Comment by xuliangzhan** [comment]
非正常的类型排序你应该使用 Array.sort 去排序

**Comment by belief-cyf** [comment]
感觉一个个table的去写自定义排序很麻烦啊。。。。 好像没有个全局定义table排序方法的地方

**Comment by xuliangzhan** [comment]
> 感觉一个个table的去写自定义排序很麻烦啊。。。。 好像没有个全局定义table排序方法的地方

这是走错片场了吧

**Comment by belief-cyf** [comment]
大佬  那个vxe-table不也是你写的嘛

**Comment by xuliangzhan** [comment]
> 大佬 那个vxe-table不也是你写的嘛

虽然是😃，但这是个工具库的 issues，不关心其他组件

**Comment by belief-cyf** [comment]
👌
