### ISSUE TITLE
请问，这是 XEUtils.browse() 对 edge 判断不正确吗？

### ISSUE THREAD

**Issue by yxb94616** [xuliangzhan/xe-utils#4]
![1564995321(1)](https://user-images.githubusercontent.com/20277731/62452113-22539a00-b7a2-11e9-8c37-3fed2dddd7e4.jpg)

**Comment by xuliangzhan** [comment]
这个得看你用的什么浏览器了

**Comment by yxb94616** [comment]
不好意思，才看到回复，当时用的是win7下的ie浏览器，edge模式，不是win10那种自带的edge浏览器

**Comment by xuliangzhan** [comment]
那有什么问题？你本来就是IE
