### ISSUE TITLE
_xeUtils.default.browse is not a function

### ISSUE THREAD

**Issue by zrx1118** [xuliangzhan/xe-utils#5]
_xeUtils.default.browse is not a function
打印了xeUtils里面没有browse这个方法啊，但是vxe-table里面的tools下面的dom.js又运用到了，这里获取browse的意思何在

**Comment by xiaoxin1991** [comment]
怎么处理的  我也出现这个问题了 389733237@qq.com 邮箱联系下

**Comment by xiaoxin1991** [comment]
https://github.com/xuliangzhan/vxe-table-demo  处理方法
