### ISSUE TITLE
var browse = _xeUtils.default.browse();

### ISSUE THREAD

**Issue by xiaoxin1991** [xuliangzhan/xe-utils#6]
升级 到最新的 错误

![image](https://user-images.githubusercontent.com/52266789/64243536-1b06e400-cf3a-11e9-9904-6d4198c0687a.png)
![image](https://user-images.githubusercontent.com/52266789/64243627-3d98fd00-cf3a-11e9-8ffb-3b2036697cc3.png)

**Comment by xuliangzhan** [comment]
#5
