### ISSUE TITLE
能否添加一个四舍五入的函数？

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/xe-utils#8]
能否添加一个四舍五入的函数？

**Comment by xuliangzhan** [comment]
四舍五入是原生支持的 1.6666.toFixed(2)

**Comment by jianliulin** [comment]
这个是银行家算法的4舍6入

**Comment by xuliangzhan** [comment]
这种特殊你只能自行实现了

**Comment by jianliulin** [comment]
原生的是“银行家算法的4舍6入，5的话要看奇偶数。” ，希望添加一个单纯的四舍五入。

**Comment by xuliangzhan** [comment]
https://www.w3school.com.cn/jsref/jsref_tofixed.asp

**Comment by xuliangzhan** [comment]
2.7+ 可以支持：round(num, digits) 四舍五入、ceil(num, digits) 向上取舍、floor(num, digits) 向下取舍
